/** Argument
 * @author  Sigma-One
 * @created 10/02/2022 21:47
 **/
class Argument internal constructor(val name: String) {
    /** The long hand flag used for this argument, for example '--help' without the leading dashes **/
    var longhand: String? = null
    /** The short hand flag used for this argument, such as '-h', without a leading dash **/
    var shorthand: Char? = null
    /** A description of this argument to be used in an autogenerated usage printout **/
    var help: String? = null
    /**
     * How many values this argument should expect to come after itself
     * Use anything below 0 to search until EOL or next flag, or 0 to not take any values
     * Defaults to 0
     **/
    var takeValues: Int = 0
}